INSERT INTO COURSE (ID, AUTHOR, NAME)
VALUES (100001, 'IN28MINUTES', 'LEARN MICROSERVICES');
INSERT INTO COURSE (ID, AUTHOR, NAME)
VALUES (100002, 'IN32MINUTES', 'LEARN MACROSERVICES');
INSERT INTO COURSE (ID, AUTHOR, NAME)
VALUES (100003, 'IN226MINUTES', 'LEARN');
INSERT INTO COURSE (ID, AUTHOR, NAME)
VALUES (100004, 'IN33HOURS', 'RUN');
